require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Excludes:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/SymbolProc:
  Enabled: false
