# fly.toml app configuration file generated for feedbackr on 2023-06-07T18:48:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feedbackr"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile.production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
